### ISSUE TITLE
Feature Request [Developement ]: No issue and PR template in github repository

### ISSUE THREAD

**Issue by SiddheshKukade** [collove/pasteme#26]
#### Solution: 
- We can add a `issue template` in the `.github/ISSUE_TEMPLATE/` folder and `.github/PULL_REQUEST_TEMPLATE/`
- This article explains benefits of Issues and Pull Request templates 

# You can assign this issue to me @SiddheshKukade

**Comment by lnxpy** [comment]
Hi Siddhesh,
Thanks for noticing this crucial necessity. PasteMe needs make-ready templates for sure. I'll assign it to you. :)

**Comment by lnxpy** [comment]
I keep this issue open till we get it done though.
