### ISSUE TITLE
Feature Request: Make the navbar toggle (hamburgur) animative!

### ISSUE THREAD

**Issue by lnxpy** [collove/pasteme#34]
Change the native Bootstrap navbar toggle to an animative element in the mobile platform! Once you clicked the button, it changes its shape X mark for example.

**Comment by SiddheshKukade** [comment]
Hi, would  like to take this one

**Comment by lnxpy** [comment]
That's awesome Siddhesh. Let's see what you got. :)

**Comment by Farhaduneci** [comment]
This one must be handled in #64, I close it here.
