### ISSUE TITLE
Feature Request: Implement expiry feature for pastes (snippets)

### ISSUE THREAD

**Issue by lnxpy** [collove/pasteme#48]
A new field for `Snippet` model to set an expiration time. (e.g. one week, one month, one year,..)
+ A management command that runs once every day and removes all the expired snippets.

**Comment by Farhaduneci** [comment]
Thank You Sadra!
I will work on this one.

**Comment by Farhaduneci** [comment]
Pastes now support Expiry feature, the default value is set to `One Day`, so that `pasteme-cli` requires some updates too! I will open a PR on that soon.

> @lnxpy Please check `pasteme-cli` [repository ](https://github.com/collove/pasteme-cli) for command line compability updates.

**Comment by lnxpy** [comment]
Thank you Farhad. :))
