### ISSUE TITLE
Frontend Refactoring (Tailwind Integration)

### ISSUE THREAD

**Issue by lnxpy** [collove/pasteme#63]
For more information, check out https://github.com/collove/pasteme/discussions/60. Thanks.

**Comment by Farhaduneci** [comment]
- [X] Navbar
- [X] Footer
- [ ] Base Template
- [ ] Snippets Template

**Comment by Farhaduneci** [comment]
First part of integration is done :heavy_check_mark:, please leave your comments below for any required changes!

> I've disabled `particlesJS` on mobile phones by default but still can hear my laptops fan while using then in background. I recommend using White/Dark images as website bg like initial design.

## Home Page Demo
![HomeDemo](https://user-images.githubusercontent.com/53964770/183236917-a03b66ac-cf02-4150-8e3d-3f495517376e.png)

## Pastes Page Demo
![PasteDemo](https://user-images.githubusercontent.com/53964770/183236915-a1f54473-ff68-40e6-a050-7e57ab1f2584.png)

**Comment by lnxpy** [comment]
In terms of `particlesJS` we may need to disable them. No backgrounds. Just the simple dark/light themes would be enough I guess. I know you've changed the colors of some sections such as the navbar but we may need the old colors back since there will be no particles anymore. :cry:

Last but not least, these templates are fantastic! Nice work! 🎉😍
